(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.

Require Export New.code.github_com.tchajed.perennial_example_proof.

Set Default Proof Using "Type".

Module ver_example.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_ver_example : IsPkgDefinedPure ver_example :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single ver_example;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_ver_example : IsPkgDefined ver_example :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single ver_example)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

Global Instance wp_func_call_Swap :
  WpFuncCall ver_example.Swap _ (is_pkg_defined ver_example) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_UseSwap :
  WpFuncCall ver_example.UseSwap _ (is_pkg_defined ver_example) :=
  ltac:(solve_wp_func_call).

End names.
End ver_example.
