(* autogenerated from github.com/tchajed/perennial-example-proof *)

From New.golang Require Import defn.
Definition ver_example : go_string := "github.com/tchajed/perennial-example-proof".

Module ver_example.

Section code.
Context `{ffi_syntax}.


Definition Swap : go_string := "github.com/tchajed/perennial-example-proof.Swap"%go.

(* go: example.go:3:6 *)
Definition Swapⁱᵐᵖˡ : val :=
  λ: "x" "y",
    exception_do (let: "y" := (mem.alloc "y") in
    let: "x" := (mem.alloc "x") in
    let: "$r0" := (![#intT] (![#ptrT] "y")) in
    let: "$r1" := (![#intT] (![#ptrT] "x")) in
    do:  ((![#ptrT] "x") <-[#intT] "$r0");;;
    do:  ((![#ptrT] "y") <-[#intT] "$r1");;;
    return: #()).

Definition vars' : list (go_string * go_type) := [].

Definition functions' : list (go_string * val) := [(Swap, Swapⁱᵐᵖˡ)].

Definition msets' : list (go_string * (list (go_string * val))) := [].

#[global] Instance info' : PkgInfo perennial_example_proof.ver_example :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [];
  |}.

Definition initialize' : val :=
  λ: <>,
    package.init #perennial_example_proof.ver_example (λ: <>,
      exception_do (do:  (package.alloc perennial_example_proof.ver_example #()))
      ).

End code.
End ver_example.
